In [2]:
import numpy as np
import pandas as pd
import csv
import os

In [3]:
df=pd.read_csv("NYC311data.csv")

/Users/angelicaestrada/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (48,49) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,32310363,12/31/15 23:59,1/1/16 0:55,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034.0,71 VERMILYEA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)"
1,32309934,12/31/15 23:59,1/1/16 1:26,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11105.0,27-07 23 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)"
2,32309159,12/31/15 23:59,1/1/16 4:51,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10458.0,2897 VALENTINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)"
3,32305098,12/31/15 23:57,1/1/16 7:43,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,10461.0,2940 BAISLEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)"
4,32306529,12/31/15 23:56,1/1/16 3:24,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373.0,87-14 57 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)"

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300698 entries, 0 to 300697
Data columns (total 53 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique Key                      300698 non-null  int64
 1   Created Date                    300698 non-null  object
 2   Closed Date                     298534 non-null  object
 3   Agency                          300698 non-null  object
 4   Agency Name                     300698 non-null  object
 5   Complaint Type                  300698 non-null  object
 6   Descriptor                      294784 non-null  object
 7   Location Type                   300567 non-null  object
 8   Incident Zip                    298083 non-null  float64
 9   Incident Address                256288 non-null  object
 10  Street Name                     256288 non-null  object
 11  Cross Street 1                  251419 non-null  object
 12  Cross Street 2                  250919 non-null  object
 13  Intersection Street 1           43858 non-null   object
 14  Intersection Street 2           43362 non-null   object
 15  Address Type                    297883 non-null  object
 16  City                            298084 non-null  object
 17  Landmark                        349 non-null     object
 18  Facility Type                   298527 non-null  object
 19  Status                          300698 non-null  object
 20  Due Date                        300695 non-null  object
 21  Resolution Description          300698 non-null  object
 22  Resolution Action Updated Date  298511 non-null  object
 23  Community Board                 300698 non-null  object
 24  Borough                         300698 non-null  object
 25  X Coordinate (State Plane)      297158 non-null  float64
 26  Y Coordinate (State Plane)      297158 non-null  float64
 27  Park Facility Name              300698 non-null  object
 28  Park Borough                    300698 non-null  object
 29  School Name                     300698 non-null  object
 30  School Number                   300698 non-null  object
 31  School Region                   300697 non-null  object
 32  School Code                     300697 non-null  object
 33  School Phone Number             300698 non-null  object
 34  School Address                  300698 non-null  object
 35  School City                     300698 non-null  object
 36  School State                    300698 non-null  object
 37  School Zip                      300697 non-null  object
 38  School Not Found                300698 non-null  object
 39  School or Citywide Complaint    0 non-null       float64
 40  Vehicle Type                    0 non-null       float64
 41  Taxi Company Borough            0 non-null       float64
 42  Taxi Pick Up Location           0 non-null       float64
 43  Bridge Highway Name             243 non-null     object
 44  Bridge Highway Direction        243 non-null     object
 45  Road Ramp                       213 non-null     object
 46  Bridge Highway Segment          213 non-null     object
 47  Garage Lot Name                 0 non-null       float64
 48  Ferry Direction                 1 non-null       object
 49  Ferry Terminal Name             2 non-null       object
 50  Latitude                        297158 non-null  float64
 51  Longitude                       297158 non-null  float64
 52  Location                        297158 non-null  object
dtypes: float64(10), int64(1), object(42)
memory usage: 121.6+ MB

In [8]:
df.describe()

,Unique Key,Incident Zip,X Coordinate (State Plane),Y Coordinate (State Plane),School or Citywide Complaint,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Garage Lot Name,Latitude,Longitude
count,3.006980e+05,298083.000000,2.971580e+05,297158.000000,0.0,0.0,0.0,0.0,0.0,297158.000000,297158.000000
mean,3.130054e+07,10848.888645,1.004854e+06,203754.534416,NaN,NaN,NaN,NaN,NaN,40.725885,-73.925630
std,5.738547e+05,583.182081,2.175338e+04,29880.183529,NaN,NaN,NaN,NaN,NaN,0.082012,0.078454
min,3.027948e+07,83.000000,9.133570e+05,121219.000000,NaN,NaN,NaN,NaN,NaN,40.499135,-74.254937
25%,3.080118e+07,10310.000000,9.919752e+05,183343.000000,NaN,NaN,NaN,NaN,NaN,40.669796,-73.972142
50%,3.130436e+07,11208.000000,1.003158e+06,201110.500000,NaN,NaN,NaN,NaN,NaN,40.718661,-73.931781
75%,3.178446e+07,11238.000000,1.018372e+06,224125.250000,NaN,NaN,NaN,NaN,NaN,40.781840,-73.876805
max,3.231065e+07,11697.000000,1.067173e+06,271876.000000,NaN,NaN,NaN,NaN,NaN,40.912869,-73.700760

In [10]:
df['Created Date']=pd.to_datetime(df['Created Date'])

In [12]:
df['Closed Date']=pd.to_datetime(df['Closed Date'])

In [14]:
df['Request_Closing_Time']=df['Closed Date']-df['Created Date']

In [15]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location,Request_Closing_Time
0,32310363,2015-12-31 23:59:00,2016-01-01 00:55:00,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034.0,71 VERMILYEA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)",0 days 00:56:00
1,32309934,2015-12-31 23:59:00,2016-01-01 01:26:00,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11105.0,27-07 23 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)",0 days 01:27:00
2,32309159,2015-12-31 23:59:00,2016-01-01 04:51:00,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10458.0,2897 VALENTINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)",0 days 04:52:00
3,32305098,2015-12-31 23:57:00,2016-01-01 07:43:00,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,10461.0,2940 BAISLEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)",0 days 07:46:00
4,32306529,2015-12-31 23:56:00,2016-01-01 03:24:00,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373.0,87-14 57 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)",0 days 03:28:00

In [23]:
missing_values = df.isna().sum()
missing_values

Unique Key                             0
Created Date                           0
Closed Date                         2164
Agency                                 0
Agency Name                            0
Complaint Type                         0
Descriptor                          5914
Location Type                        131
Incident Zip                        2615
Incident Address                   44410
Street Name                        44410
Cross Street 1                     49279
Cross Street 2                     49779
Intersection Street 1             256840
Intersection Street 2             257336
Address Type                        2815
City                                2614
Landmark                          300349
Facility Type                       2171
Status                                 0
Due Date                               3
Resolution Description                 0
Resolution Action Updated Date      2187
Community Board                        0
Borough                                0
X Coordinate (State Plane)          3540
Y Coordinate (State Plane)          3540
Park Facility Name                     0
Park Borough                           0
School Name                            0
School Number                          0
School Region                          1
School Code                            1
School Phone Number                    0
School Address                         0
School City                            0
School State                           0
School Zip                             1
School Not Found                       0
School or Citywide Complaint      300698
Vehicle Type                      300698
Taxi Company Borough              300698
Taxi Pick Up Location             300698
Bridge Highway Name               300455
Bridge Highway Direction          300455
Road Ramp                         300485
Bridge Highway Segment            300485
Garage Lot Name                   300698
Ferry Direction                   300697
Ferry Terminal Name               300696
Latitude                            3540
Longitude                           3540
Location                            3540
Request_Closing_Time                2164
dtype: int64

In [24]:
def convert_lowercase(df):
    #convert string columns into lowercase to elimintae duplication
    df = df.applymap(lambda s:s.lower() if type(s) == str else s)
    return df

In [26]:
df = convert_lowercase(df)
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location,Request_Closing_Time
0,32310363,2015-12-31 23:59:00,2016-01-01 00:55:00,nypd,new york city police department,noise - street/sidewalk,loud music/party,street/sidewalk,10034.0,71 vermilyea avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)",0 days 00:56:00
1,32309934,2015-12-31 23:59:00,2016-01-01 01:26:00,nypd,new york city police department,blocked driveway,no access,street/sidewalk,11105.0,27-07 23 avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)",0 days 01:27:00
2,32309159,2015-12-31 23:59:00,2016-01-01 04:51:00,nypd,new york city police department,blocked driveway,no access,street/sidewalk,10458.0,2897 valentine avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)",0 days 04:52:00
3,32305098,2015-12-31 23:57:00,2016-01-01 07:43:00,nypd,new york city police department,illegal parking,commercial overnight parking,street/sidewalk,10461.0,2940 baisley avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)",0 days 07:46:00
4,32306529,2015-12-31 23:56:00,2016-01-01 03:24:00,nypd,new york city police department,illegal parking,blocked sidewalk,street/sidewalk,11373.0,87-14 57 road,...,NaN,NaN,NaN,NaN,NaN,NaN,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)",0 days 03:28:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300693,30281872,2015-03-29 00:33:00,NaT,nypd,new york city police department,noise - commercial,loud music/party,club/bar/restaurant,NaN,crescent avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
300694,30281230,2015-03-29 00:33:00,2015-03-29 02:33:00,nypd,new york city police department,blocked driveway,partial access,street/sidewalk,11418.0,100-17 87 avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.694077,-73.846087,"(40.69407728322387, -73.8460866160573)",0 days 02:00:00
300695,30283424,2015-03-29 00:33:00,2015-03-29 03:40:00,nypd,new york city police department,noise - commercial,loud music/party,club/bar/restaurant,11206.0,162 throop avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.699590,-73.944234,"(40.69959035300927, -73.94423377144169)",0 days 03:07:00
300696,30280004,2015-03-29 00:33:00,2015-03-29 04:38:00,nypd,new york city police department,noise - commercial,loud music/party,club/bar/restaurant,10461.0,3151 east tremont avenue,...,NaN,NaN,NaN,NaN,NaN,NaN,40.837708,-73.834587,"(40.8377075854206, -73.83458731019586)",0 days 04:05:00
300697,30281825,2015-03-29 00:33:00,2015-03-29 04:41:00,nypd,new york city police department,noise - commercial,loud music/party,store/commercial,10036.0,251 west 48 street,...,NaN,NaN,NaN,NaN,NaN,NaN,40.760583,-73.985922,"(40.76058322950115, -73.98592204392392)",0 days 04:08:00

In [44]:
#drop columns that are almost empty
def drop_empty_columns(df,threshold=.085):
    #col with missing values
    col_count=df.isna().sum().where(lambda x:x>0).dropna()
    #cols to be drop
    
    columns_to_drop = []
    
    #iterate through columns wih missing values
    for col,miss_values in col_count.iteritems():
        
        if (miss_values/len(df) >= threshold):
            columns_to_drop.append(col)
            
    df.drop(columns= columns_to_drop,axis=1,inplace=True)

    return df

In [45]:
df=drop_empty_columns(df,threshold=.085)
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Address Type,...,School Phone Number,School Address,School City,School State,School Zip,School Not Found,Latitude,Longitude,Location,Request_Closing_Time
0,32310363,2015-12-31 23:59:00,2016-01-01 00:55:00,nypd,new york city police department,noise - street/sidewalk,loud music/party,street/sidewalk,10034.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)",0 days 00:56:00
1,32309934,2015-12-31 23:59:00,2016-01-01 01:26:00,nypd,new york city police department,blocked driveway,no access,street/sidewalk,11105.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)",0 days 01:27:00
2,32309159,2015-12-31 23:59:00,2016-01-01 04:51:00,nypd,new york city police department,blocked driveway,no access,street/sidewalk,10458.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)",0 days 04:52:00
3,32305098,2015-12-31 23:57:00,2016-01-01 07:43:00,nypd,new york city police department,illegal parking,commercial overnight parking,street/sidewalk,10461.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)",0 days 07:46:00
4,32306529,2015-12-31 23:56:00,2016-01-01 03:24:00,nypd,new york city police department,illegal parking,blocked sidewalk,street/sidewalk,11373.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)",0 days 03:28:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300693,30281872,2015-03-29 00:33:00,NaT,nypd,new york city police department,noise - commercial,loud music/party,club/bar/restaurant,NaN,NaN,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,NaN,NaN,NaN,NaT
300694,30281230,2015-03-29 00:33:00,2015-03-29 02:33:00,nypd,new york city police department,blocked driveway,partial access,street/sidewalk,11418.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.694077,-73.846087,"(40.69407728322387, -73.8460866160573)",0 days 02:00:00
300695,30283424,2015-03-29 00:33:00,2015-03-29 03:40:00,nypd,new york city police department,noise - commercial,loud music/party,club/bar/restaurant,11206.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.699590,-73.944234,"(40.69959035300927, -73.94423377144169)",0 days 03:07:00
300696,30280004,2015-03-29 00:33:00,2015-03-29 04:38:00,nypd,new york city police department,noise - commercial,loud music/party,club/bar/restaurant,10461.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.837708,-73.834587,"(40.8377075854206, -73.83458731019586)",0 days 04:05:00
300697,30281825,2015-03-29 00:33:00,2015-03-29 04:41:00,nypd,new york city police department,noise - commercial,loud music/party,store/commercial,10036.0,address,...,unspecified,unspecified,unspecified,unspecified,unspecified,n,40.760583,-73.985922,"(40.76058322950115, -73.98592204392392)",0 days 04:08:00

In [41]:
df.isna().sum().where(lambda x:x>0).dropna()

Closed Date                       2164.0
Descriptor                        5914.0
Location Type                      131.0
Incident Zip                      2615.0
Address Type                      2815.0
City                              2614.0
Facility Type                     2171.0
Due Date                             3.0
Resolution Action Updated Date    2187.0
X Coordinate (State Plane)        3540.0
Y Coordinate (State Plane)        3540.0
School Region                        1.0
School Code                          1.0
School Zip                           1.0
Latitude                          3540.0
Longitude                         3540.0
Location                          3540.0
Request_Closing_Time              2164.0
dtype: float64